### ISSUE TITLE
Maven Repository Issue

### ISSUE THREAD

**Issue by saminitz** [Drednote/spring-boot-starter-telegram#21]
Hi there,

I tried to add you library to my project but I get the following error:

```
[ERROR] dependency: io.github.drednote:spring-boot-starter-telegram:jar:0.3.0 (compile)
[ERROR]         io.github.drednote:spring-boot-starter-telegram:jar:0.3.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
```

I looked into the repository at https://repo.maven.apache.org/maven2/io/github/drednote/spring-boot-starter-telegram/0.3.0/ and noticed that the version does not match with the jar file listed there.
The version I took a look at was `0.3.0` but there was no file 
`spring-boot-starter-telegram-0.3.0.jar` only
`spring-boot-starter-telegram-0.3.0-plain.jar`
I don't know if that is the issue but looking at other repositories, they all have a file matching the exact version.

**Comment by Drednote** [comment]
Hello!

Thanks for notifying me about the error connecting the library.

I have already fixed this issue and made the necessary changes to the code. All fixes are in the following [pull request](https://github.com/Drednote/spring-boot-starter-telegram/pull/22). Today I will post a new version 0.3.1 in maven.

If you have further problems, be sure to write about them!
